### ISSUE TITLE
Sha numbers not recognized

### ISSUE THREAD

**Issue by redevill** [frux/csp-header#10]
Hello,

When using this library, I found that cps.INLINE constant would work, but 'unsafe-inline' would not. I mention this because when trying to use 'sha256-ASTASFGA23SDGA23' as a string constant, this also does not work. Obviously we can't have const for all sha #.

Was wondering if there was a quick fix for this?
Thanks

**Comment by frux** [comment]
> Hello,
> 
> When using this library, I found that cps.INLINE constant would work, but 'unsafe-inline' would not. I mention this because when trying to use 'sha256-ASTASFGA23SDGA23' as a string constant, this also does not work. Obviously we can't have const for all sha #.
> 
> Was wondering if there was a quick fix for this?
> Thanks

Hi, @redevill. I've just tried to reproduce this on npm playground and this code
```js
var csp = require("csp-header")

console.log(csp({
    policies: {
        'script-src': [ "'unsafe-inline'" ]
    }
}));
```

return a string `"script-src 'unsafe-inline';"` as expected.

Can you show example?

**Comment by redevill** [comment]
Thanks!, that solves the issue. Syntax problem, as I was just using the single quotes, and not the "'Sha256-blahblah'" combined single and double.
